import pandas as pd

# Full hard-coded data with correct country information
data = [
    {'CarBrandId': 1, 'CarBrandTitle': 'آرتابان (ای ام جی)', 'CarBrandTitleEn': 'amg', 'CarBrandSlug': 'amg', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 2, 'CarBrandTitle': 'آریسان', 'CarBrandTitleEn': 'arisun', 'CarBrandSlug': 'arisun', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 3, 'CarBrandTitle': 'آلفارومئو', 'CarBrandTitleEn': 'alfaromeo', 'CarBrandSlug': 'alfaromeo', 'CountryTitle': 'ایتالیا', 'CountryTitleEn': 'Italy', 'CountrySlug': 'italy'},
    {'CarBrandId': 4, 'CarBrandTitle': 'آمیکو', 'CarBrandTitleEn': 'amico', 'CarBrandSlug': 'amico', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 5, 'CarBrandTitle': 'آئودی', 'CarBrandTitleEn': 'audi', 'CarBrandSlug': 'audi', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 6, 'CarBrandTitle': 'اپل', 'CarBrandTitleEn': 'opel', 'CarBrandSlug': 'opel', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 7, 'CarBrandTitle': 'اس دبلیو ام', 'CarBrandTitleEn': 'swm', 'CarBrandSlug': 'swm', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 8, 'CarBrandTitle': 'اسکای ول', 'CarBrandTitleEn': 'skywell', 'CarBrandSlug': 'skywell', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 9, 'CarBrandTitle': 'اسمارت', 'CarBrandTitleEn': 'smart', 'CarBrandSlug': 'smart', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 10, 'CarBrandTitle': 'اشکودا', 'CarBrandTitleEn': 'skoda', 'CarBrandSlug': 'skoda', 'CountryTitle': 'جمهوری چک', 'CountryTitleEn': 'Czech Republic', 'CountrySlug': 'czech-republic'},
    {'CarBrandId': 11, 'CarBrandTitle': 'اطلس', 'CarBrandTitleEn': 'atlas', 'CarBrandSlug': 'atlas', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 12, 'CarBrandTitle': 'اکستریم', 'CarBrandTitleEn': 'xtrim', 'CarBrandSlug': 'xtrim', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 13, 'CarBrandTitle': 'ام جی', 'CarBrandTitleEn': 'mg', 'CarBrandSlug': 'mg', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 14, 'CarBrandTitle': 'ام وی ام', 'CarBrandTitleEn': 'mvm', 'CarBrandSlug': 'mvm', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 15, 'CarBrandTitle': 'اوتار', 'CarBrandTitleEn': 'avatr', 'CarBrandSlug': 'avatr', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 16, 'CarBrandTitle': 'اونترا', 'CarBrandTitleEn': 'aventra', 'CarBrandSlug': 'aventra', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 17, 'CarBrandTitle': 'ایرس', 'CarBrandTitleEn': 'eres', 'CarBrandSlug': 'eres', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 18, 'CarBrandTitle': 'ایسوزو', 'CarBrandTitleEn': 'isuzu', 'CarBrandSlug': 'isuzu', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 19, 'CarBrandTitle': 'اینرودز', 'CarBrandTitleEn': 'inroads', 'CarBrandSlug': 'inroads', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 20, 'CarBrandTitle': 'اینفینیت', 'CarBrandTitleEn': 'infinite', 'CarBrandSlug': 'infinite', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 21, 'CarBrandTitle': 'ب ام و', 'CarBrandTitleEn': 'bmw', 'CarBrandSlug': 'bmw', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 22, 'CarBrandTitle': 'بایک', 'CarBrandTitleEn': 'baic', 'CarBrandSlug': 'baic', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 23, 'CarBrandTitle': 'برلیانس', 'CarBrandTitleEn': 'brilliance', 'CarBrandSlug': 'brilliance', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 24, 'CarBrandTitle': 'بسترن', 'CarBrandTitleEn': 'besturn', 'CarBrandSlug': 'besturn', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 25, 'CarBrandTitle': 'بستیون', 'CarBrandTitleEn': 'bestune', 'CarBrandSlug': 'bestune', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 26, 'CarBrandTitle': 'بنز', 'CarBrandTitleEn': 'mercedesbenz', 'CarBrandSlug': 'mercedesbenz', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 27, 'CarBrandTitle': 'بورگوارد', 'CarBrandTitleEn': 'borgward', 'CarBrandSlug': 'borgward', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 28, 'CarBrandTitle': 'بی ای دبلیو (BAW)', 'CarBrandTitleEn': 'baw', 'CarBrandSlug': 'baw', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 29, 'CarBrandTitle': 'بی ای سی', 'CarBrandTitleEn': 'bac', 'CarBrandSlug': 'bac', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 30, 'CarBrandTitle': 'بی وای دی', 'CarBrandTitleEn': 'byd', 'CarBrandSlug': 'byd', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 31, 'CarBrandTitle': 'بیجینگ', 'CarBrandTitleEn': 'beijing', 'CarBrandSlug': 'beijing', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 32, 'CarBrandTitle': 'بیسو', 'CarBrandTitleEn': 'bisu', 'CarBrandSlug': 'bisu', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 33, 'CarBrandTitle': 'پادرا موتور', 'CarBrandTitleEn': 'padramotors', 'CarBrandSlug': 'padramotors', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 34, 'CarBrandTitle': 'پارس نوآ', 'CarBrandTitleEn': 'parsnoa', 'CarBrandSlug': 'parsnoa', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 35, 'CarBrandTitle': 'پراید', 'CarBrandTitleEn': 'pride', 'CarBrandSlug': 'pride', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 36, 'CarBrandTitle': 'پژو', 'CarBrandTitleEn': 'peugeot', 'CarBrandSlug': 'peugeot', 'CountryTitle': 'فرانسه', 'CountryTitleEn': 'France', 'CountrySlug': 'france'},
    {'CarBrandId': 37, 'CarBrandTitle': 'پورشه', 'CarBrandTitleEn': 'porsche', 'CarBrandSlug': 'porsche', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 38, 'CarBrandTitle': 'پیکان', 'CarBrandTitleEn': 'peykan', 'CarBrandSlug': 'peykan', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 39, 'CarBrandTitle': 'تارا', 'CarBrandTitleEn': 'tara', 'CarBrandSlug': 'tara', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 40, 'CarBrandTitle': 'تانک', 'CarBrandTitleEn': 'tank', 'CarBrandSlug': 'tank', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 41, 'CarBrandTitle': 'تویوتا', 'CarBrandTitleEn': 'toyota', 'CarBrandSlug': 'toyota', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 42, 'CarBrandTitle': 'تیبا', 'CarBrandTitleEn': 'tiba', 'CarBrandSlug': 'tiba', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 43, 'CarBrandTitle': 'تیگارد', 'CarBrandTitleEn': 'tigardmotor', 'CarBrandSlug': 'tigardmotor', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 44, 'CarBrandTitle': 'جتا', 'CarBrandTitleEn': 'jetta', 'CarBrandSlug': 'jetta', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 45, 'CarBrandTitle': 'جک', 'CarBrandTitleEn': 'jac', 'CarBrandSlug': 'jac', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 46, 'CarBrandTitle': 'جِی ام سی (JMC)', 'CarBrandTitleEn': 'jmc', 'CarBrandSlug': 'jmc', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 47, 'CarBrandTitle': 'جی ای سی', 'CarBrandTitleEn': 'gacgonow', 'CarBrandSlug': 'gacgonow', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 48, 'CarBrandTitle': 'جیلی', 'CarBrandTitleEn': 'geely', 'CarBrandSlug': 'geely', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 49, 'CarBrandTitle': 'چانگان', 'CarBrandTitleEn': 'changan', 'CarBrandSlug': 'changan', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 50, 'CarBrandTitle': 'چری', 'CarBrandTitleEn': 'chery', 'CarBrandSlug': 'chery', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 51, 'CarBrandTitle': 'دامای', 'CarBrandTitleEn': 'domy', 'CarBrandSlug': 'domy', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 52, 'CarBrandTitle': 'دانگ فنگ', 'CarBrandTitleEn': 'dongfeng', 'CarBrandSlug': 'dongfeng', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 53, 'CarBrandTitle': 'دایون', 'CarBrandTitleEn': 'dayun', 'CarBrandSlug': 'dayun', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 54, 'CarBrandTitle': 'دنا', 'CarBrandTitleEn': 'dena', 'CarBrandSlug': 'dena', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 55, 'CarBrandTitle': 'دوو', 'CarBrandTitleEn': 'daewoo', 'CarBrandSlug': 'daewoo', 'CountryTitle': 'کره جنوبی', 'CountryTitleEn': 'South Korea', 'CountrySlug': 'south-korea'},
    {'CarBrandId': 56, 'CarBrandTitle': 'دی اس', 'CarBrandTitleEn': 'ds', 'CarBrandSlug': 'ds', 'CountryTitle': 'فرانسه', 'CountryTitleEn': 'France', 'CountrySlug': 'france'},
    {'CarBrandId': 57, 'CarBrandTitle': 'دیگنیتی', 'CarBrandTitleEn': 'dignity', 'CarBrandSlug': 'dignity', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 58, 'CarBrandTitle': 'رانا', 'CarBrandTitleEn': 'runna', 'CarBrandSlug': 'runna', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 59, 'CarBrandTitle': 'راین', 'CarBrandTitleEn': 'rayen', 'CarBrandSlug': 'rayen', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 60, 'CarBrandTitle': 'رنو', 'CarBrandTitleEn': 'renault', 'CarBrandSlug': 'renault', 'CountryTitle': 'فرانسه', 'CountryTitleEn': 'France', 'CountrySlug': 'france'},
    {'CarBrandId': 61, 'CarBrandTitle': 'روئوه', 'CarBrandTitleEn': 'roewe', 'CarBrandSlug': 'roewe', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 62, 'CarBrandTitle': 'ری را', 'CarBrandTitleEn': 'reera', 'CarBrandSlug': 'reera', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 63, 'CarBrandTitle': 'ریسپکت', 'CarBrandTitleEn': 'respect', 'CarBrandSlug': 'respect', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 64, 'CarBrandTitle': 'ریگان', 'CarBrandTitleEn': 'rigan', 'CarBrandSlug': 'rigan', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 65, 'CarBrandTitle': 'زامیاد', 'CarBrandTitleEn': 'zamyad', 'CarBrandSlug': 'zamyad', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 66, 'CarBrandTitle': 'زد ایکس اتو', 'CarBrandTitleEn': 'zxauto', 'CarBrandSlug': 'zxauto', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 67, 'CarBrandTitle': 'زوتی', 'CarBrandTitleEn': 'zotye', 'CarBrandSlug': 'zotye', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 68, 'CarBrandTitle': 'سانگ یانگ', 'CarBrandTitleEn': 'ssangyong', 'CarBrandSlug': 'ssangyong', 'CountryTitle': 'کره جنوبی', 'CountryTitleEn': 'South Korea', 'CountrySlug': 'south-korea'},
    {'CarBrandId': 69, 'CarBrandTitle': 'ساینا', 'CarBrandTitleEn': 'saina', 'CarBrandSlug': 'saina', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 70, 'CarBrandTitle': 'سمند', 'CarBrandTitleEn': 'samand', 'CarBrandSlug': 'samand', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 71, 'CarBrandTitle': 'سوزوکی', 'CarBrandTitleEn': 'suzuki', 'CarBrandSlug': 'suzuki', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 72, 'CarBrandTitle': 'سوئیست', 'CarBrandTitleEn': 'soueast', 'CarBrandSlug': 'soueast', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 73, 'CarBrandTitle': 'سهند', 'CarBrandTitleEn': 'sahand', 'CarBrandSlug': 'sahand', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 74, 'CarBrandTitle': 'سیتروئن', 'CarBrandTitleEn': 'citroen', 'CarBrandSlug': 'citroen', 'CountryTitle': 'فرانسه', 'CountryTitleEn': 'France', 'CountrySlug': 'france'},
    {'CarBrandId': 75, 'CarBrandTitle': 'سئات', 'CarBrandTitleEn': 'seat', 'CarBrandSlug': 'seat', 'CountryTitle': 'اسپانیا', 'CountryTitleEn': 'Spain', 'CountrySlug': 'spain'},
    {'CarBrandId': 76, 'CarBrandTitle': 'شاهین', 'CarBrandTitleEn': 'shahin', 'CarBrandSlug': 'shahin', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 77, 'CarBrandTitle': 'فردا', 'CarBrandTitleEn': 'farda', 'CarBrandSlug': 'farda', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 78, 'CarBrandTitle': 'فوتون', 'CarBrandTitleEn': 'foton', 'CarBrandSlug': 'foton', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 79, 'CarBrandTitle': 'فولکس', 'CarBrandTitleEn': 'volkswagen', 'CarBrandSlug': 'volkswagen', 'CountryTitle': 'آلمان', 'CountryTitleEn': 'Germany', 'CountrySlug': 'germany'},
    {'CarBrandId': 80, 'CarBrandTitle': 'فونیکس', 'CarBrandTitleEn': 'fownix', 'CarBrandSlug': 'fownix', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 81, 'CarBrandTitle': 'فیات', 'CarBrandTitleEn': 'fiat', 'CarBrandSlug': 'fiat', 'CountryTitle': 'ایتالیا', 'CountryTitleEn': 'Italy', 'CountrySlug': 'italy'},
    {'CarBrandId': 82, 'CarBrandTitle': 'فیدلیتی', 'CarBrandTitleEn': 'fidelity', 'CarBrandSlug': 'fidelity', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 83, 'CarBrandTitle': 'کاپرا', 'CarBrandTitleEn': 'capra', 'CarBrandSlug': 'capra', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 84, 'CarBrandTitle': 'کارا', 'CarBrandTitleEn': 'cara', 'CarBrandSlug': 'cara', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 85, 'CarBrandTitle': 'کوییک', 'CarBrandTitleEn': 'quick', 'CarBrandSlug': 'quick', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 86, 'CarBrandTitle': 'کی ام سی', 'CarBrandTitleEn': 'kmc', 'CarBrandSlug': 'kmc', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 87, 'CarBrandTitle': 'کیا', 'CarBrandTitleEn': 'kia', 'CarBrandSlug': 'kia', 'CountryTitle': 'کره جنوبی', 'CountryTitleEn': 'South Korea', 'CountrySlug': 'south-korea'},
    {'CarBrandId': 88, 'CarBrandTitle': 'گریت وال', 'CarBrandTitleEn': 'greatwall', 'CarBrandSlug': 'greatwall', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 89, 'CarBrandTitle': 'لاماری', 'CarBrandTitleEn': 'lamari', 'CarBrandSlug': 'lamari', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 90, 'CarBrandTitle': 'لاماکو', 'CarBrandTitleEn': 'lamaco', 'CarBrandSlug': 'lamaco', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 91, 'CarBrandTitle': 'لکسوس', 'CarBrandTitleEn': 'lexus', 'CarBrandSlug': 'lexus', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 92, 'CarBrandTitle': 'لندرور', 'CarBrandTitleEn': 'landrover', 'CarBrandSlug': 'landrover', 'CountryTitle': 'بریتانیا', 'CountryTitleEn': 'United Kingdom', 'CountrySlug': 'united-kingdom'},
    {'CarBrandId': 93, 'CarBrandTitle': 'لندمارک', 'CarBrandTitleEn': 'landmark', 'CarBrandSlug': 'landmark', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 94, 'CarBrandTitle': 'لوتوس', 'CarBrandTitleEn': 'lotus', 'CarBrandSlug': 'lotus', 'CountryTitle': 'بریتانیا', 'CountryTitleEn': 'United Kingdom', 'CountrySlug': 'united-kingdom'},
    {'CarBrandId': 95, 'CarBrandTitle': 'لوکانو', 'CarBrandTitleEn': 'lucano', 'CarBrandSlug': 'lucano', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 96, 'CarBrandTitle': 'لونا', 'CarBrandTitleEn': 'luna', 'CarBrandSlug': 'luna', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 97, 'CarBrandTitle': 'لیپ موتور', 'CarBrandTitleEn': 'leapmotor', 'CarBrandSlug': 'leapmotor', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 98, 'CarBrandTitle': 'لیفان', 'CarBrandTitleEn': 'lifan', 'CarBrandSlug': 'lifan', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 99, 'CarBrandTitle': 'مازراتی', 'CarBrandTitleEn': 'maserati', 'CarBrandSlug': 'maserati', 'CountryTitle': 'ایتالیا', 'CountryTitleEn': 'Italy', 'CountrySlug': 'italy'},
    {'CarBrandId': 100, 'CarBrandTitle': 'مزدا', 'CarBrandTitleEn': 'mazda', 'CarBrandSlug': 'mazda', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 101, 'CarBrandTitle': 'مکث موتور', 'CarBrandTitleEn': 'maxmotor', 'CarBrandSlug': 'maxmotor', 'CountryTitle': 'ایران', 'CountryTitleEn': 'Iran', 'CountrySlug': 'iran'},
    {'CarBrandId': 102, 'CarBrandTitle': 'مکسوس', 'CarBrandTitleEn': 'maxus', 'CarBrandSlug': 'maxus', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 103, 'CarBrandTitle': 'میتسوبیشی', 'CarBrandTitleEn': 'mitsubishi', 'CarBrandSlug': 'mitsubishi', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 104, 'CarBrandTitle': 'مینی', 'CarBrandTitleEn': 'mini', 'CarBrandSlug': 'mini', 'CountryTitle': 'بریتانیا', 'CountryTitleEn': 'United Kingdom', 'CountrySlug': 'united-kingdom'},
    {'CarBrandId': 105, 'CarBrandTitle': 'نوو', 'CarBrandTitleEn': 'nevo', 'CarBrandSlug': 'nevo', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 106, 'CarBrandTitle': 'نیسان', 'CarBrandTitleEn': 'nissan', 'CarBrandSlug': 'nissan', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 107, 'CarBrandTitle': 'ولوو', 'CarBrandTitleEn': 'volvo', 'CarBrandSlug': 'volvo', 'CountryTitle': 'سوئد', 'CountryTitleEn': 'Sweden', 'CountrySlug': 'sweden'},
    {'CarBrandId': 108, 'CarBrandTitle': 'ونوسیا', 'CarBrandTitleEn': 'venucia', 'CarBrandSlug': 'venucia', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 109, 'CarBrandTitle': 'وویا', 'CarBrandTitleEn': 'voyah', 'CarBrandSlug': 'voyah', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 110, 'CarBrandTitle': 'هاوال', 'CarBrandTitleEn': 'haval', 'CarBrandSlug': 'haval', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 111, 'CarBrandTitle': 'هایما', 'CarBrandTitleEn': 'haima', 'CarBrandSlug': 'haima', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 112, 'CarBrandTitle': 'هن تنگ', 'CarBrandTitleEn': 'hanteng', 'CarBrandSlug': 'hanteng', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 113, 'CarBrandTitle': 'هوندا', 'CarBrandTitleEn': 'honda', 'CarBrandSlug': 'honda', 'CountryTitle': 'ژاپن', 'CountryTitleEn': 'Japan', 'CountrySlug': 'japan'},
    {'CarBrandId': 114, 'CarBrandTitle': 'هونگچی', 'CarBrandTitleEn': 'hongqi', 'CarBrandSlug': 'hongqi', 'CountryTitle': 'چین', 'CountryTitleEn': 'China', 'CountrySlug': 'china'},
    {'CarBrandId': 115, 'CarBrandTitle': 'هیوندای', 'CarBrandTitleEn': 'hyundai', 'CarBrandSlug': 'hyundai', 'CountryTitle': 'کره جنوبی', 'CountryTitleEn': 'South Korea', 'CountrySlug': 'south-korea'},
    {'CarBrandId': 116, 'CarBrandTitle': 'یوآز', 'CarBrandTitleEn': 'uaz', 'CarBrandSlug': 'uaz', 'CountryTitle': 'روسیه', 'CountryTitleEn': 'Russia', 'CountrySlug': 'russia'}
]

# Create DataFrame and save to Excel
df = pd.DataFrame(data)
df.to_excel('apps/brand-country/data/completed_brandsAndCountry.xlsx', index=False)

print('✅ File "completed_brandsAndCountry.xlsx" created successfully!')
print('   It contains all 116 brands with correct country data.')